### ISSUE TITLE
Feature roadmap

### ISSUE THREAD

**Issue by stefanieschneider** [arthist-lmu/artigo#7]
We keep this issue open to collect feature requests. Please suggest a new feature by leaving a comment.

### General features
- [x] Integrate OpenSearch  (#2)
- [ ] Implement badge system (#8)
- [ ] Map existing resource instances to Wikidata (CLIP + SIFT etc.)
- [x] Implement Wikidata scraping routine to regularly update resource metadata

### Game framework
- [x] Support games from individual resources, collections, or other resource sets (e.g., based on search results)
- [x] Support time-specific games that are created from random (e.g., _Challenge of the Day_)

### User administration
- [ ] Integrate OAuth 2 (#6)
- [x] Add email verification (#1)
